// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "用户登录接口，支持邮箱或用户名登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "账号登录",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.LoginResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "用户注册接口，需要提供用户名、邮箱和密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.Response"
                        }
                    }
                }
            }
        },
        "/usage": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取用户在指定时间范围内的流量使用量统计数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "获取用户流量使用量",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID，可选",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "虚拟网络ID，可选，空值表示所有虚拟网络",
                        "name": "vnetId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "时间范围：24h(24小时), 7d(7天), 30d(30天), month(按月), all(全部)",
                        "name": "range",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.GetUsageResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取当前登录用户的详细信息，包括用户基本信息、活跃隧道数、在线设备数等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.GetProfileResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "修改用户的基本信息，包括用户名和邮箱",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "修改用户信息",
                "parameters": [
                    {
                        "description": "修改用户信息请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.Response"
                        }
                    }
                }
            }
        },
        "/user/group": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取当前用户的组信息，用于商城套餐显示",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "获取用户组信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.GetUserGroupResponse"
                        }
                    }
                }
            }
        },
        "/user/password": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "修改用户密码，需要验证当前密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "修改密码请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.Response"
                        }
                    }
                }
            }
        },
        "/user/purchase": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "购买增值服务套餐，传入套餐号(2=青铜,3=白银,4=黄金)和购买时长(1-12个月)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "购买增值服务套餐",
                "parameters": [
                    {
                        "description": "购买套餐请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.PurchasePackageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.PurchasePackageResponse"
                        }
                    }
                }
            }
        },
        "/vnet": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取当前用户的所有虚拟网络",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "虚拟网络模块"
                ],
                "summary": "获取用户的虚拟网络列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.GetVnetByUserIdResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "为当前用户创建新的虚拟网络",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "虚拟网络模块"
                ],
                "summary": "创建虚拟网络",
                "parameters": [
                    {
                        "description": "创建虚拟网络请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.CreateVnetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.Response"
                        }
                    }
                }
            }
        },
        "/vnet/limit": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取当前用户的虚拟网络限制和使用情况",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "虚拟网络模块"
                ],
                "summary": "获取用户的虚拟网络限制信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.GetVNetLimitInfoResponse"
                        }
                    }
                }
            }
        },
        "/vnet/{vnetId}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新用户的虚拟网络配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "虚拟网络模块"
                ],
                "summary": "更新虚拟网络",
                "parameters": [
                    {
                        "type": "string",
                        "description": "虚拟网络ID，用于标识要更新的虚拟网络",
                        "name": "vnetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新虚拟网络请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.UpdateVnetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除用户的虚拟网络",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "虚拟网络模块"
                ],
                "summary": "删除虚拟网络",
                "parameters": [
                    {
                        "type": "string",
                        "description": "虚拟网络ID，用于标识要删除的虚拟网络",
                        "name": "vnetId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hyacinth-backend_api_v1.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "hyacinth-backend_api_v1.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "currentPassword",
                "newPassword"
            ],
            "properties": {
                "currentPassword": {
                    "type": "string",
                    "example": "123456"
                },
                "newPassword": {
                    "type": "string",
                    "example": "654321"
                }
            }
        },
        "hyacinth-backend_api_v1.CreateVnetRequest": {
            "type": "object",
            "properties": {
                "clientsLimit": {
                    "type": "integer",
                    "example": 10
                },
                "comment": {
                    "type": "string",
                    "example": "我的虚拟网络"
                },
                "enableDHCP": {
                    "type": "boolean",
                    "example": true
                },
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "ipRange": {
                    "type": "string",
                    "example": "192.168.1.0/24"
                },
                "password": {
                    "type": "string",
                    "example": "1234"
                },
                "token": {
                    "type": "string",
                    "example": "1234"
                },
                "vnetId": {
                    "type": "string",
                    "example": "1234"
                }
            }
        },
        "hyacinth-backend_api_v1.GetProfileResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/hyacinth-backend_api_v1.GetProfileResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "hyacinth-backend_api_v1.GetProfileResponseData": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "activeTunnels": {
                    "type": "integer"
                },
                "availableTraffic": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "1234@gmail.com"
                },
                "isVip": {
                    "type": "boolean"
                },
                "onlineDevices": {
                    "type": "integer"
                },
                "privilegeExpiry": {
                    "type": "string"
                },
                "userGroup": {
                    "type": "integer"
                },
                "userGroupName": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "alan"
                }
            }
        },
        "hyacinth-backend_api_v1.GetUsageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/hyacinth-backend_api_v1.GetUsageResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "hyacinth-backend_api_v1.GetUsageResponseData": {
            "type": "object",
            "properties": {
                "usages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hyacinth-backend_api_v1.UsageData"
                    }
                }
            }
        },
        "hyacinth-backend_api_v1.GetUserGroupResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/hyacinth-backend_api_v1.GetUserGroupResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "hyacinth-backend_api_v1.GetUserGroupResponseData": {
            "type": "object",
            "properties": {
                "userGroup": {
                    "type": "integer"
                }
            }
        },
        "hyacinth-backend_api_v1.GetVNetLimitInfoResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/hyacinth-backend_api_v1.GetVNetLimitInfoResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "hyacinth-backend_api_v1.GetVNetLimitInfoResponseData": {
            "type": "object",
            "properties": {
                "currentCount": {
                    "type": "integer",
                    "example": 2
                },
                "maxClientsLimitPerVNet": {
                    "type": "integer",
                    "example": 10
                },
                "maxLimit": {
                    "type": "integer",
                    "example": 5
                },
                "userGroup": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "hyacinth-backend_api_v1.GetVnetByUserIdResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/hyacinth-backend_api_v1.GetVnetResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "hyacinth-backend_api_v1.GetVnetByUserIdResponseItem": {
            "type": "object",
            "properties": {
                "clientsLimit": {
                    "type": "integer",
                    "example": 10
                },
                "clientsOnline": {
                    "type": "integer",
                    "example": 5
                },
                "comment": {
                    "type": "string",
                    "example": "我的虚拟网络"
                },
                "enableDHCP": {
                    "type": "boolean",
                    "example": true
                },
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "ipRange": {
                    "type": "string",
                    "example": "192.168.1.0/24"
                },
                "password": {
                    "type": "string",
                    "example": "1234"
                },
                "token": {
                    "type": "string",
                    "example": "1234"
                },
                "vnetId": {
                    "type": "string",
                    "example": "1234"
                }
            }
        },
        "hyacinth-backend_api_v1.GetVnetResponseData": {
            "type": "object",
            "properties": {
                "vnets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hyacinth-backend_api_v1.GetVnetByUserIdResponseItem"
                    }
                }
            }
        },
        "hyacinth-backend_api_v1.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "usernameOrEmail"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "usernameOrEmail": {
                    "type": "string",
                    "example": "1234@gmail.com"
                }
            }
        },
        "hyacinth-backend_api_v1.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/hyacinth-backend_api_v1.LoginResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "hyacinth-backend_api_v1.LoginResponseData": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                }
            }
        },
        "hyacinth-backend_api_v1.PurchasePackageRequest": {
            "type": "object",
            "required": [
                "packageType"
            ],
            "properties": {
                "duration": {
                    "description": "购买时长（月数），1-12个月",
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1,
                    "example": 1
                },
                "packageType": {
                    "description": "2=青铜 3=白银 4=黄金",
                    "type": "integer",
                    "maximum": 4,
                    "minimum": 2,
                    "example": 2
                }
            }
        },
        "hyacinth-backend_api_v1.PurchasePackageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "hyacinth-backend_api_v1.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "1234@gmail.com"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "alan"
                }
            }
        },
        "hyacinth-backend_api_v1.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "hyacinth-backend_api_v1.UpdateProfileRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "1234@gmail.com"
                },
                "username": {
                    "type": "string",
                    "example": "alan"
                }
            }
        },
        "hyacinth-backend_api_v1.UpdateVnetRequest": {
            "type": "object",
            "properties": {
                "clientsLimit": {
                    "type": "integer",
                    "example": 10
                },
                "comment": {
                    "type": "string",
                    "example": "我的虚拟网络"
                },
                "enableDHCP": {
                    "type": "boolean",
                    "example": true
                },
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "ipRange": {
                    "type": "string",
                    "example": "192.168.1.0/24"
                },
                "password": {
                    "type": "string",
                    "example": "1234"
                },
                "token": {
                    "type": "string",
                    "example": "1234"
                },
                "vnetId": {
                    "type": "string",
                    "example": "1234"
                }
            }
        },
        "hyacinth-backend_api_v1.UsageData": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "usage": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Nunu Example API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
